### ISSUE TITLE
Negative expectations hang

### ISSUE THREAD

**Issue by dblock** [dblock/ocmock-expecta#1]
See https://github.com/dblock/ocmock-expecta/blob/master/EXPMatchers%2BOCMock/EXPMatchers%2BOCMockTests/EXPMatchers%2BOCMockSpecs.m#L18.

**Comment by gfontenot** [comment]
It looks like it's actually a memory issue. Looked into it a bit today, and `actual` has already been released when the match block runs. I don't know enough about the internals of Expecta to know what's going on beyond that, but it's at least a start.

**Comment by foulkesjohn** [comment]
Only seems to happen when uppercaseString is called. If you try length it works fine. 

For uppercaseString the call stack looks like its stuck in an infinite recursion loop, theres nothing clearly wrong with it. I've tried messing with where and how the s variable in created but it doesn't seem to change anything

**Comment by orta** [comment]
Closing, don't think this is an issue anymore, none of that code exists anymore.
