### ISSUE TITLE
Failing with exception on primitive return types

### ISSUE THREAD

**Issue by pietbrauer** [dblock/ocmock-expecta#7]
Given the following test:

``` objective-c
- (void)testLastIndexPathWithZeroSection {
    UICollectionViewLayout *layout = [[UICollectionViewLayout alloc] init];
    UICollectionView *collectionView = [UICollectionView alloc] initWithFrame:CGRectMake(0, 0, 320, 500) collectionViewLayout:layout];
    @mockify(collectionView);
    expect(collectionView).to.receive(@selector(numberOfSections)).returning(@0);
    expect([collectionView lastIndexPath]).beFalsy();
}
```

I get an exception in line [97](https://github.com/dblock/ocmock-expecta/blob/master/Expecta%2BOCMock.m#L97). The return type should be `NSInteger` and I think it is not retainable.

```
Printing description of invocation:
<NSInvocation: 0x7fe2442be6c0>
return value: {q} 1
target: {@} 0x7fe2430ea000
selector: {:} numberOfSections
Printing description of cfResult:
(CFTypeRef) cfResult = 0x0000000000000001
Printing description of self->_returning:
0
```

I think the solution should be to find out if the pointer can be bridged to `NSObject` and then retain it and else treat it as a primitive but I was unable to do it somehow.

Maybe you got another idea?

**Comment by orta** [comment]
I've taken a stab at this, with a passing test case:

```
- (NSInteger)method4 { return 23; };

and

it(@"checks for a return value bridged to an object", ^{
    @mockify(sut);
    expect(sut).receive(@selector(method4)).returning(@23);
    [sut method4];
});
```

This currently only takes on NSIntegers, could definitely expand out as needed.

**Comment by pietbrauer** [comment]
I was so close :+1: was missing the `@encode(id)` thingy. Will try it out!
